- name: Install nginx
  ansible.builtin.apt:
    name:
      - nginx
    state: present

- name: Copy nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

- name: Disable default nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Delete default nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: Add deluge repo
  ansible.builtin.apt_repository:
    repo: ppa:deluge-team/stable
    state: present

- name: Install deluge
  ansible.builtin.apt:
    name:
      - deluged
      - deluge-web
      - deluge-console
      - deluge-common
    state: present

- name: Create deluge group
  ansible.builtin.group:
    name: deluge
    state: present

- name: Create deluge user
  ansible.builtin.user:
    name: deluge
    password: '!'
    home: /var/lib/deluge
    create_home: true
    system: true
    group: deluge
    comment: Deluge Service

- name: Copy deluged.service file
  ansible.builtin.copy:
    src: deluged.service
    dest: /etc/systemd/system/deluged.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart deluged
    - Reload systemd

- name: Copy deluge-web.service file
  ansible.builtin.copy:
    src: deluge-web.service
    dest: /etc/systemd/system/deluge-web.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart deluge-web
    - Reload systemd

- name: Enable and start deluged service
  ansible.builtin.systemd_service:
    name: deluged
    enabled: true
    state: started
    daemon_reload: true

- name: Enable and start deluge-web service
  ansible.builtin.systemd_service:
    name: deluge-web
    enabled: true
    state: started
    daemon_reload: true

- name: Copy proxy-control.conf
  ansible.builtin.copy:
    src: proxy-control.conf
    dest: /etc/nginx/proxy-control.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

- name: Copy Deluge site file
  ansible.builtin.template:
    src: deluge.j2
    dest: /etc/nginx/sites-available/deluge
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

- name: Enable Deluge site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/deluge
    dest: /etc/nginx/sites-enabled/deluge
    owner: root
    group: root
    state: link
  notify: Restart nginx
