- name: Install nginx
  ansible.builtin.apt:
    name:
      - nginx
    state: present
  when: ansible_facts["os_family"] == "Debian"

- name: Install nginx
  ansible.builtin.dnf:
    name:
      - nginx
    state: present
  when: ansible_facts["os_family"] == "RedHat"

- name: Copy nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

- name: Disable default nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: nginx_delete_default_site

- name: Delete default nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-available/default
    state: absent
  when: nginx_delete_default_site

- name: Enable and start nginx
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state: started
  when: nginx_enable_and_start
