- name: Create slskd group
  ansible.builtin.group:
    name: slskd
    state: present

- name: Create slskd user
  ansible.builtin.user:
    name: slskd
    password: '!'
    home: /var/lib/slskd
    create_home: true
    system: true
    group: slskd
    comment: slskd Service

- name: Install slskd
  ansible.builtin.include_role:
    name: brianreumere.util.install_from_url
  vars:
    install_from_url_name: slskd
    install_from_url_version: "{{ slskd_version }}"
    install_from_url_download_url: "{{ slskd_download_url }}"
    install_from_url_checksum: "{{ slskd_checksum }}"
    install_from_url_install_cmd: |
      ls -lah
      cp slskd {{ slskd_install_dir.rstrip('/') }}/slskd
      chmod 0755 {{ slskd_install_dir.rstrip('/') }}/slskd
    install_from_url_creates:
      - "{{ slskd_install_dir.rstrip('/') }}/slskd"

- name: Copy slskd.service file
  ansible.builtin.copy:
    src: slskd.service
    dest: /etc/systemd/system/slskd.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart slskd
    - Reload systemd

- name: Copy slskd config
  ansible.builtin.template:
    src: slskd.yml.j2
    dest: /var/lib/slskd/slskd.yml
    owner: slskd
    group: slskd
    mode: '0644'
  notify: Restart slskd

- name: Enable and start slskd service
  ansible.builtin.systemd_service:
    name: slskd
    enabled: true
    state: started
    daemon_reload: true

- name: Copy slskd site file
  ansible.builtin.template:
    src: slskd.j2
    dest: /etc/nginx/sites-available/slskd
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

- name: Enable slskd site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/slskd
    dest: /etc/nginx/sites-enabled/slskd
    owner: root
    group: root
    state: link
  notify: Restart nginx
