---
dependencies: []
galaxy_info:
  role_name: acme_sh
  description: Install and configure acme.sh
  author: Brian Reumere <brian@mutualaid.info>
  license: ISC
  min_ansible_version: '2.15'
  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: GenericLinux
      versions:
        - all
    - name: OpenBSD
      versions:
        - all
    - name: FreeBSD
      versions:
        - all
