---
- name: Install Grafana GPG key
  ansible.builtin.rpm_key:
    key: https://rpm.grafana.com/gpg.key
    state: present

- name: Copy Grafana repo file
  copy:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo
    owner: root
    group: root
    mode: '0644'

- name: Install Grafana
  ansible.builtin.dnf:
    name: grafana
    state: present
    update_cache: true

- name: Copy grafana.ini
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: '0640'
  notify: Restart Grafana

- name: Copy Grafana nginx config
  ansible.builtin.template:
    src: grafana.conf.j2
    dest: /etc/nginx/conf.d/grafana.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

- name: Start and enable Grafana
  ansible.builtin.systemd_service:
    name: grafana-server
    state: started
    enabled: true
