---
- name: Include variables for RHEL (and compatible)
  ansible.builtin.include_vars:
    file: 
  when: ansible_os_family == "RedHat"

- name: Include variables for Debian (and compatible)
  when: ansible_os_family == "Debian"

- name: Include variables for other OSes
  when:
    - ansible_os_family != "RedHat"
    - ansible_os_family != "Debian"

- name: Install Wordfence CLI
  ansible.builtin.include_role:
    name: brianreumere.util.install_from_url
  vars:
    install_from_url_name: wordfence_cli
    install_from_url_version: "{{ wordfence_cli_version }}"
    install_from_url_download_url: "{{ wordfence_cli_download_url }}"
    install_from_url_checksum: "{{ wordfence_cli_checksum }}"
    install_from_url_install_cmd: "{{ wordfence_cli_install_cmd }}"
    install_from_url_creates:
      - "{{ acme_sh_home }}"

- name: Create custom facts directory
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    owner: root
    group: root
    mode: '0700'
    state: directory

- name: Install Plex Media Server
  ansible.builtin.dnf:
    name: plexmediaserver
    state: present
    update_cache: true
  notify: Restart nginx

- name: Enable and start Plex Media Server
  ansible.builtin.systemd_service:
    name: plexmediaserver
    enabled: true
    state: started

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
    update_cache: true
  when: plex_reverse_proxy

- name: Create dhparam.pem for Plex
  ansible.builtin.shell:
    cmd: |
      openssl dhparam -out /etc/ssl/dhparam.pem 2048
      chown root:root /etc/ssl/dhparam.pem
      chmod 0444 /etc/ssl/dhparam.pem
    creates: /etc/ssl/dhparam.pem
  when: plex_reverse_proxy

- name: Copy nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx
  when: plex_reverse_proxy

- name: Set SELinux boolean
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
  when: plex_reverse_proxy

- name: Enable and start nginx
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state: started
  when: plex_reverse_proxy
