- name: Restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted

- name: Restart slskd
  ansible.builtin.systemd_service:
    name: slskd
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
