namespace: brianreumere
name: software
version: false
readme: README.md
authors:
  - Brian Reumere <brian@mutualaid.info>
description: Ansible collection for software
license:
  - ISC
repository: https://github.com/brianreumere/brianreumere.software
