---
namespace: brianreumere
name: software
version: 1.0.0  # This will be replaced by the build workflow
readme: README.md
authors:
  - Brian Reumere <brian@mutualaid.info>
description: Ansible collection for software
license:
  - ISC
tags:
  - application
  - linux
repository: https://github.com/brianreumere/brianreumere.software
