---
- name: Create shiori user
  ansible.builtin.user:
    name: shiori
    home: /var/lib/shiori
    shell: /usr/sbin/nologin

- name: Install shiori
  ansible.builtin.include_role:
    name: brianreumere.util.install_from_url
  vars:
    install_from_url_name: shiori
    install_from_url_version: "{{ shiori_version }}"
    install_from_url_download_url: "{{ shiori_download_url }}"
    install_from_url_checksum: "{{ shiori_checksum }}"
    install_from_url_install_cmd: |
      cp shiori /usr/local/bin/shiori
      chown root:root /usr/local/bin/shiori
      chmod 0755 /usr/local/bin/shiori
    install_from_url_creates:
      - /usr/local/bin/shiori

- name: Copy shiori service file
  ansible.builtin.copy:
    src: shiori.service
    dest: /etc/systemd/system/shiori.service
    owner: root
    group: root
    mode: 0644
  notify: Restart shiori

- name: Start and enable shiori service
  ansible.builtin.systemd_service:
    name: shiori
    state: started
    enabled: true
    daemon_reload: true

- name: Install Apache
  ansible.builtin.dnf:
    name:
      - httpd
      - mod_ssl
    state: present
    update_cache: true

- name: Copy disabled welcome.conf
  ansible.builtin.copy:
    src: welcome.conf
    dest: /etc/httpd/conf.d/welcome.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart httpd

- name: Copy Shiori Apache config
  ansible.builtin.template:
    src: shiori.conf.j2
    dest: /etc/httpd/conf.d/shiori.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart httpd

- name: Start and enable Apache
  service:
    name: httpd
    state: started
    enabled: true
