---
- name: Create pds user
  ansible.builtin.user:
    name: _pds
    password: '*************'
    home: /var/pds
    create_home: true
    system: true
    group: _pds
    comment: AT Protocol PDS

- name: Install Node.js and other dependencies
  community.general.openbsd_pkg:
    name:
      - node
      - libvips
      - sqlite3
    state: present

- name: Install NPM packages
  ansible.builtin.command:
    cmd: npm install @atproto/pds dotenv
    chdir: /var/pds
    creates: /var/pds/node_modules

- name: Create PDS data directory
  ansible.builtin.file:
    path: "{{ pds_data_directory }}"
    state: directory
    owner: _pds
    group: _pds
    mode: '0755'

- name: Copy pds.env file
  ansible.builtin.template:
    src: pds.env.j2
    dest: /var/pds/.env
    owner: _pds
    group: _pds
    mode: '0640'

- name: Copy index.mjs file
  ansible.builtin.copy:
    src: index.mjs
    dest: /var/pds/index.mjs
    owner: _pds
    group: _pds
    mode: '0750'

- name: Copy pds rc.d service file
  ansible.builtin.copy:
    src: pds
    dest: /etc/rc.d/pds
    owner: root
    group: wheel
    mode: '0555'
