---
- name: Install porkbun-automatic-dns
  ansible.builtin.include_role:
    name: brianreumere.util.install_from_url
  vars:
    install_from_url_name: porkbun-automatic-dns
    install_from_url_version: "{{ porkbun_automatic_dns_version }}"
    install_from_url_download_url: "{{ porkbun_automatic_dns_download_url }}"
    install_from_url_checksum: "{{ porkbun_automatic_dns_checksum }}"
    install_from_url_install_cmd: |
      cp pbad {{ porkbun_automatic_dns_install_dir.rstrip('/') }}/pbad
      chmod 0755 {{ porkbun_automatic_dns_install_dir.rstrip('/') }}/pbad
    install_from_url_creates:
      - "{{ porkbun_automatic_dns_install_dir.rstrip('/') }}/pbad"

- name: Create porkbun-automatic-dns keyfile
  ansible.builtin.template:
    src: porkbunapi.j2
    dest: "~{{ ansible_env.DOAS_USER if 'DOAS_USER' in ansible_env else ansible_env.SUDO_USER }}/.porkbunapi"
    mode: '0600'

- name: Schedule porkbun-automatic-dns cronjob
  ansible.builtin.cron:
    name: porkbun-automatic-dns
    user: "{{ porkbun_automatic_dns_cron_user }}"
    minute: "{{ porkbun_automatic_dns_cron_minute }}"
    hour: "{{ porkbun_automatic_dns_cron_hour }}"
    day: "{{ porkbun_automatic_dns_cron_day_of_month }}"
    month: "{{ porkbun_automatic_dns_cron_month }}"
    weekday: "{{ porkbun_automatic_dns_cron_day_of_week }}"
    job: "\
      {{ porkbun_automatic_dns_install_dir.rstrip('/') }}/pbad\
      {% if porkbun_automatic_dns_ipv6 %} -6{% endif %}\
      {% if porkbun_automatic_dns_ext_ip_method == 'stdin' %} -s{% endif %}\
      {% if porkbun_automatic_dns_ext_ip_method == 'extif' %} -i {{ porkbun_automatic_dns_ext_if }}{% endif %}\
      {% if porkbun_automatic_dns_custom_keyfile %} -p {{ porkbun_automatic_dns_custom_keyfile }}{% endif %}\
      {% if porkbun_automatic_dns_ttl %} -l {{ porkbun_automatic_dns_ttl }}{% endif %} \
      -d {{ porkbun_automatic_dns_domain }} \
      -r \"{{ porkbun_automatic_dns_record_names | join(' ') }}\""
