---
- name: Restart httpd
  ansible.builtin.systemd_service:
    name: httpd
    state: restarted

- name: Restart Postfix
  ansible.builtin.systemd_service:
    name: postfix
    state: restarted

- name: Restart Redis
  ansible.builtin.systemd_service:
    name: redis
    state: restarted

- name: Restart PHP-FPM
  ansible.builtin.systemd_service:
    name: php-fpm
    state: restarted
