---
- name: Restart httpd
  service:
    name: httpd
    state: restarted

- name: Restart Postfix
  service:
    name: postfix
    state: restarted

- name: Restart Redis
  service:
    name: redis
    state: restarted

- name: Restart PHP-FPM
  service:
    name: php-fpm
    state: restarted
