---
porkbun_automatic_dns_version: '1.0.0'
porkbun_automatic_dns_download_url: 'https://github.com/brianreumere/porkbun-automatic-dns/archive/refs/tags/v{{ porkbun_automatic_dns_version }}.tar.gz'
porkbun_automatic_dns_checksum: 'sha256:7e5cf492b9961ba851fa2ee7ad04303a684d497a76bfd0bc6e36d0c3e391a6a1'
porkbun_automatic_dns_install_dir: /usr/local/bin
porkbun_automatic_dns_ipv6: false
porkbun_automatic_dns_ext_ip_method: porkbun
porkbun_automatic_dns_custom_keyfile: false
porkbun_automatic_dns_ttl: false
porkbun_automatic_dns_cron_user: "{{ ansible_env.DOAS_USER if 'DOAS_USER' in ansible_env else ansible_env.SUDO_USER }}"
porkbun_automatic_dns_cron_minute: '*/15'
porkbun_automatic_dns_cron_hour: '*'
porkbun_automatic_dns_cron_day_of_month: '*'
porkbun_automatic_dns_cron_month: '*'
porkbun_automatic_dns_cron_day_of_week: '*'
