---
slskd_version: '0.22.1'
slskd_download_url: 'https://github.com/slskd/slskd/releases/download/0.22.1/slskd-0.22.1-linux-x64.zip'
slskd_checksum: 'sha256:d9fa525fb5eb515752ae2e709a7ba4767a355ff6e36c3f0604823d10006bb596'
slskd_install_dir: /var/lib/slskd/app
slskd_incomplete_directory: /var/lib/slskd/incomplete
slskd_downloads_directory: /var/lib/slskd/downloads
