- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Restart deluged
  service:
    name: deluged
    state: restarted

- name: Restart deluge-web
  service:
    name: deluge-web
    state: restarted

- name: Reload systemd
  systemd:
    daemon_reload: true
