- name: Restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted

- name: Restart deluged
  ansible.builtin.systemd_service:
    name: deluged
    state: restarted

- name: Restart deluge-web
  ansible.builtin.systemd_service:
    name: deluge-web
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
