---
- name: Restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted

- name: Restart Grafana
  ansible.builtin.systemd_service:
    name: grafana-server
    state: restarted
