# https://support.plex.tv/articles/235974187-enable-repository-updating-for-supported-linux-server-distributions/
---
- name: Set crypto policies fact (to only run once)
  ansible.builtin.set_fact:
    plex_crypto_policies_applied: true

- name: Set crypto policies (Plex repository only supports SHA-1)
  ansible.builtin.shell:
    cmd: update-crypto-policies --set DEFAULT:SHA1
  when: not plex_crypto_policies_applied

- name: Import Plex repository GPG key
  ansible.builtin.rpm_key:
    key: https://downloads.plex.tv/plex-keys/PlexSign.key

- name: Add Plex repository
  ansible.builtin.yum_repository:
    name: PlexRepo
    description: PlexRepo
    file: plex
    baseurl: https://downloads.plex.tv/repo/rpm/$basearch/
    enabled: true
    gpgkey: https://downloads.plex.tv/plex-keys/PlexSign.key
    gpgcheck: true
    repo_gpgcheck: true

- name: Install Plex Media Server
  ansible.builtin.dnf:
    name: plexmediaserver
    state: present
    update_cache: true
  notify: Restart nginx

- name: Enable and start Plex Media Server
  ansible.builtin.systemd_service:
    name: plexmediaserver
    enabled: true
    state: started

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
    update_cache: true
  when: plex_reverse_proxy

- name: Create dhparam.pem for Plex
  ansible.builtin.shell:
    cmd: |
      openssl dhparam -out /etc/ssl/dhparam.pem 2048
      chown root:root /etc/ssl/dhparam.pem
      chmod 0444 /etc/ssl/dhparam.pem
    creates: /etc/ssl/dhparam.pem
  when: plex_reverse_proxy

- name: Copy nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart nginx
  when: plex_reverse_proxy

- name: Set SELinux boolean
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
  when: plex_reverse_proxy

- name: Enable and start nginx
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state: started
  when: plex_reverse_proxy
